import { Chore } from './types';

export const DEFAULT_CHORES: Chore[] = [
  {
    id: 'make-bed',
    labels: {
      en: 'Make Bed',
      de: 'Bett machen',
      fr: 'Faire le lit',
      pt: 'Arrumar a cama',
    },
    value: 0.5,
    frequency: 'Daily',
    effort: 'Low',
    category: 'bedroom',
  },
  {
    id: 'laundry-hang',
    labels: {
      en: 'Hang Laundry',
      de: 'Wäsche aufhängen',
      fr: 'Étendre le linge',
      pt: 'Estender a roupa',
    },
    value: 2,
    frequency: '2x/Week',
    effort: 'Medium',
    category: 'laundry',
  },
  {
    id: 'laundry-fold',
    labels: {
      en: 'Fold Laundry',
      de: 'Wäsche falten',
      fr: 'Plier le linge',
      pt: 'Dobrar a roupa',
    },
    value: 2,
    frequency: '2x/Week',
    effort: 'Medium',
    category: 'laundry',
  },
  {
    id: 'laundry-put-away',
    labels: {
      en: 'Put Away Laundry',
      de: 'Wäsche wegräumen',
      fr: 'Ranger le linge',
      pt: 'Guardar a roupa',
    },
    value: 0.5,
    frequency: '2x/Week',
    effort: 'Low',
    category: 'laundry',
  },
  {
    id: 'dishwasher-empty',
    labels: {
      en: 'Empty the Dishwasher',
      de: 'Spülmaschine ausräumen',
      fr: 'Vider le lave-vaisselle',
      pt: 'Esvaziar a máquina de lavar louça',
    },
    value: 1,
    frequency: '3x/Week',
    effort: 'Medium',
    category: 'kitchen',
  },
  {
    id: 'table-set',
    labels: {
      en: 'Set Table',
      de: 'Tisch decken',
      fr: 'Mettre la table',
      pt: 'Pôr a mesa',
    },
    value: 0.25,
    frequency: 'Daily',
    effort: 'Low',
    category: 'kitchen',
  },
  {
    id: 'table-clean',
    labels: {
      en: 'Clean Table',
      de: 'Tisch abräumen',
      fr: 'Débarrasser la table',
      pt: 'Limpar a mesa',
    },
    value: 0.25,
    frequency: 'Daily',
    effort: 'Low',
    category: 'kitchen',
  },
  {
    id: 'cook',
    labels: {
      en: 'Help with Cooking',
      de: 'Beim Kochen helfen',
      fr: 'Aider à cuisiner',
      pt: 'Ajudar a cozinhar',
    },
    value: 1.5,
    frequency: 'Daily',
    effort: 'High',
    category: 'kitchen',
  },
  {
    id: 'tidy-living-room',
    labels: {
      en: 'Tidy-up the Living Room',
      de: 'Wohnzimmer aufräumen',
      fr: 'Ranger le salon',
      pt: 'Arrumar a sala',
    },
    value: 1,
    frequency: 'Daily',
    effort: 'Medium',
    category: 'living-room',
  },
  {
    id: 'tidy-bedroom',
    labels: {
      en: 'Tidy-up the Bedroom',
      de: 'Schlafzimmer aufräumen',
      fr: 'Ranger la chambre',
      pt: 'Arrumar o quarto',
    },
    value: 1,
    frequency: 'Daily',
    effort: 'Medium',
    category: 'bedroom',
  },
];
