import { Bed, Sofa, Utensils, Trees, Bath, Shirt, Home } from "lucide-react";
import { Chore, ChoreCategory, ChoreCategoryId } from "./types";

export const CHORE_CATEGORIES: Record<ChoreCategoryId, ChoreCategory> = {
  bedroom: {
    id: "bedroom",
    color: "yellow",
    icon: Bed,
    labels: {
      en: "Bedroom",
      de: "Schlafzimmer",
      fr: "Chambre",
      pt: "Quarto",
    },
  },
  "living-room": {
    id: "living-room",
    color: "purple",
    icon: Sofa,
    labels: {
      en: "Living Room",
      de: "Wohnzimmer",
      fr: "Salon",
      pt: "Sala de Estar",
    },
  },
  kitchen: {
    id: "kitchen",
    color: "green",
    icon: Utensils,
    labels: {
      en: "Kitchen",
      de: "Küche",
      fr: "Cuisine",
      pt: "Cozinha",
    },
  },
  bathroom: {
    id: "bathroom",
    color: "blue",
    icon: Bath,
    labels: {
      en: "Bathroom",
      de: "Badezimmer",
      fr: "Salle de bain",
      pt: "Banheiro",
    },
  },
  outside: {
    id: "outside",
    color: "green",
    icon: Trees,
    labels: {
      en: "Outside",
      de: "Draußen",
      fr: "Extérieur",
      pt: "Exterior",
    },
  },
  laundry: {
    id: "laundry",
    color: "orange",
    icon: Shirt,
    labels: {
      en: "Laundry",
      de: "Wäsche",
      fr: "Buanderie",
      pt: "Lavanderia",
    },
  },
  household: {
    id: "household",
    color: "pink",
    icon: Home,
    labels: {
      en: "Household",
      de: "Haushalt",
      fr: "Ménage",
      pt: "Casa",
    },
  },
};

export const DEFAULT_CHORES: Chore[] = [
  {
    id: "make-bed",
    labels: {
      en: "Make Bed",
      de: "Bett machen",
      fr: "Faire le lit",
      pt: "Arrumar a cama",
    },
    value: 0.25,
    frequency: "Daily",
    effort: "low",
    category: "bedroom",
  },
  {
    id: "laundry-hang",
    labels: {
      en: "Hang Laundry",
      de: "Wäsche aufhängen",
      fr: "Étendre le linge",
      pt: "Estender a roupa",
    },
    value: 1,
    frequency: "2x/Week",
    effort: "medium",
    category: "laundry",
  },
  {
    id: "laundry-fold",
    labels: {
      en: "Fold Laundry",
      de: "Wäsche falten",
      fr: "Plier le linge",
      pt: "Dobrar a roupa",
    },
    value: 2,
    frequency: "2x/Week",
    effort: "medium",
    category: "laundry",
  },
  {
    id: "laundry-put-away",
    labels: {
      en: "Put Away Laundry",
      de: "Wäsche wegräumen",
      fr: "Ranger le linge",
      pt: "Guardar a roupa",
    },
    value: 0.25,
    frequency: "2x/Week",
    effort: "low",
    category: "laundry",
  },
  {
    id: "dishwasher-empty",
    labels: {
      en: "Empty the Dishwasher",
      de: "Spülmaschine ausräumen",
      fr: "Vider le lave-vaisselle",
      pt: "Esvaziar a máquina de lavar louça",
    },
    value: 1,
    frequency: "3x/Week",
    effort: "medium",
    category: "kitchen",
  },
  {
    id: "table-set",
    labels: {
      en: "Set Table",
      de: "Tisch decken",
      fr: "Mettre la table",
      pt: "Pôr a mesa",
    },
    value: 0.25,
    frequency: "Daily",
    effort: "low",
    category: "kitchen",
  },
  {
    id: "table-clean",
    labels: {
      en: "Clean Table",
      de: "Tisch abräumen",
      fr: "Débarrasser la table",
      pt: "Limpar a mesa",
    },
    value: 0.25,
    frequency: "Daily",
    effort: "low",
    category: "kitchen",
  },
  {
    id: "tidy-living-room",
    labels: {
      en: "Tidy-up the Living Room",
      de: "Wohnzimmer aufräumen",
      fr: "Ranger le salon",
      pt: "Arrumar a sala",
    },
    value: 0.5,
    frequency: "Daily",
    effort: "medium",
    category: "living-room",
  },
  {
    id: "tidy-bedroom",
    labels: {
      en: "Tidy-up the Bedroom",
      de: "Schlafzimmer aufräumen",
      fr: "Ranger la chambre",
      pt: "Arrumar o quarto",
    },
    value: 0.5,
    frequency: "Daily",
    effort: "medium",
    category: "bedroom",
  },
  {
    id: "bathroom-sink-clean",
    labels: {
      en: "Clean the Bathroom Sink",
      de: "Waschbecken reinigen",
      fr: "Nettoyer le lavabo",
      pt: "Limpar o lavatório",
    },
    value: 1,
    frequency: "Weekly",
    effort: "medium",
    category: "bathroom",
  },
  {
    id: "vacuuming",
    labels: {
      en: "Vacuum Floors",
      de: "Staubsaugen",
      fr: "Passer l’aspirateur",
      pt: "Aspirar o chão",
    },
    value: 2.5,
    frequency: "Weekly",
    effort: "high",
    category: "household",
  },
  {
    id: "trash-out",
    labels: {
      en: "Take out the Trash",
      de: "Müll rausbringen",
      fr: "Sortir les poubelles",
      pt: "Tirar o lixo",
    },
    value: 1.5,
    frequency: "2x/Week",
    effort: "high",
    category: "household",
  },
];
